src/Entity/Forfaits.php
<?php

namespace App\Entity;

use App\Repository\ForfaitsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ForfaitsRepository::class)
 */
class Forfaits
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lib_forfait;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descr_forfait;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_forfait;

    /**
     * @ORM\ManyToOne(targetEntity=Services::class, inversedBy="forfaits")
     */
    private $services;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibForfait(): ?string
    {
        return $this->lib_forfait;
    }

    public function setLibForfait(string $lib_forfait): self
    {
        $this->lib_forfait = $lib_forfait;

        return $this;
    }

    public function getDescrForfait(): ?string
    {
        return $this->descr_forfait;
    }

    public function setDescrForfait(?string $descr_forfait): self
    {
        $this->descr_forfait = $descr_forfait;

        return $this;
    }

    public function getPrixForfait(): ?float
    {
        return $this->prix_forfait;
    }

    public function setPrixForfait(float $prix_forfait): self
    {
        $this->prix_forfait = $prix_forfait;

        return $this;
    }

    public function getServices(): ?Services
    {
        return $this->services;
    }

    public function setServices(?Services $services): self
    {
        $this->services = $services;

        return $this;
    }
}

src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ImagesRepository::class)
 */
class Images
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $lib_img;

    /**
     * @ORM\ManyToOne(targetEntity=Services::class, inversedBy="images")
     */
    private $services;

        /**
     * @ORM\ManyToOne(targetEntity=Services::class, inversedBy="images")
     */
    private $pages;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $descr_img;

    public function __construct()
    {
        // $this->pages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibImg(): ?string
    {
        return $this->lib_img;
    }

    public function setLibImg(?string $lib_img): self
    {
        $this->lib_img = $lib_img;

        return $this;
    }

    public function getServices(): ?Services
    {
        return $this->services;
    }

    public function setServices(?Services $services): self
    {
        $this->services = $services;

        return $this;
    }

    public function getDescrImg(): ?string
    {
        return $this->descr_img;
    }

    public function setDescrImg(?string $descr_img): self
    {
        $this->descr_img = $descr_img;

        return $this;
    }

    public function __toString() {
        return (string) $this->lib_img;
    }

    public function getPages(): ?Pages
    {
        return $this->pages_id;
    }

    public function setPages(?Pages $pages): self
    {
        $this->pages_id = $pages;

        return $this;
    }

}

src/Entity/Pages.php
<?php

namespace App\Entity;

use App\Repository\PagesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PagesRepository::class)
 */
class Pages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $lib_page;

    /**
     * @ORM\Column(type="text")
     */
    private $bloc1;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $bloc2;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $bloc3;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $bloc4;

    /**
     * @ORM\ManyToOne(targetEntity=Services::class, inversedBy="pages")
     */
    private $services;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $metadescr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $metakw;

    public function __construct()
    {
        // $this->services = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibPage(): ?string
    {
        return $this->lib_page;
    }

    public function setLibPage(string $lib_page): self
    {
        $this->lib_page = $lib_page;

        return $this;
    }

    public function getBloc1(): ?string
    {
        return $this->bloc1;
    }

    public function setBloc1(string $bloc1): self
    {
        $this->bloc1 = $bloc1;

        return $this;
    }

    public function getBloc2(): ?string
    {
        return $this->bloc2;
    }

    public function setBloc2(?string $bloc2): self
    {
        $this->bloc2 = $bloc2;

        return $this;
    }

    public function getBloc3(): ?string
    {
        return $this->bloc3;
    }

    public function setBloc3(?string $bloc3): self
    {
        $this->bloc3 = $bloc3;

        return $this;
    }

    public function getBloc4(): ?string
    {
        return $this->bloc4;
    }

    public function setBloc4(?string $bloc4): self
    {
        $this->bloc4 = $bloc4;

        return $this;
    }

    public function getServices(): ?Services
    {
        return $this->services;
    }

    public function setServices(?Services $services): self
    {
        $this->services = $services;

        return $this;
    }

    public function getMetadescr(): ?string
    {
        return $this->metadescr;
    }

    public function setMetadescr(?string $metadescr): self
    {
        $this->metadescr = $metadescr;

        return $this;
    }

    public function getMetakw(): ?string
    {
        return $this->metakw;
    }

    public function setMetakw(?string $metakw): self
    {
        $this->metakw = $metakw;

        return $this;
    }
}

src/Controller/PageEntretienController.php
<?php

namespace App\Controller;

use App\Repository\ForfaitsRepository;
use App\Repository\ImagesRepository;
use App\Repository\PagesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PageEntretienController extends AbstractController
{
    /**
     * @Route("/entretien", name="page_entretien")
     */
    public function index(PagesRepository $pr, ForfaitsRepository $fr, ImagesRepository $ir): Response
    {
        $currentPage = 'Entretien';
        $pageData = $pr->findOneByTitle($currentPage);
        $service = $pageData->getServices();
        $forfaitsData = $fr->findByServices($service);
        
        $carrousel = $ir->findByService($service);
        $images = $ir->findOneByService($service);

        return $this->render('page_entretien/index.html.twig', [
            'currentPage' => $currentPage,
            'page' => $pageData, 
            'forfaits'=>$forfaitsData, 
            'carrousel' => $carrousel,
            'images' => $images,
            'service' => $service,
            'pageData' => $pageData,
            'forfaitsData' => $forfaitsData,

        ]);
    }
}

templates/page_entretien/index.html.twig
{% extends 'base_front.html.twig' %}


{% block meta %}
	<meta name="description" content="{{page.metadescr}}">
	<meta name="keywords" content="{{page.metakw}}">
{% endblock %}

{% block title %}
	{{ page.libPage }}
{% endblock %}

{% block body %}
	<main
		class="container py-5 position">

		<!-- Corps -->
		<section class="d-flex row justify-content-center mb-5 pb-5 ">
			<div class="col-12 text-center mb-3">
				<h3>
					<font color="#cc0000">
						{{ page.libPage }}
						toutes marques</font>
				</h3>
			</div>

			<div class="col-lg-8 col-md-12 justify-content-center row d-flex">
				<article class="row d-flex justify-content-center col-12 py-3 mx-auto">
					<div class="col-lg-4 col-md-12 align-self-center mb-2">
						{% for image1 in images %}
							{% if loop.first %}
								{% if image1 %}
									<img src="/img/{{image1.libImg}}" class="w-100 d-block mx-auto" alt="/img/{{image1.descrImg}}">
								{% else %}
									<img src="/img/default.png" class="w-50 d-block mx-auto" alt="/img/default.png">
								{% endif %}
							{% endif %}
						{% endfor %}
					</div>

					<div class="col-lg-8 col-md-12 justify-content-center align-self-center">
						<p>{{page.bloc1|raw}}</p>
					</div>
				</article>

				<article class="row d-flex justify-content-center col-12 py-3 mx-auto">
					<div class="col-lg-8 col-md-12 mb-2 align-self-center justify-content-center">
						<p>{{page.bloc2|raw}}</p>
					</div>
					<div class="col-lg-4 col-md-12 align-self-center">
						{% for image2 in images %}
							{% if loop.last %}
								{% if image2 %}
									<img src="/img/{{image2.libImg}}" class="w-100 d-block mx-auto" alt="/img/{{image2.descrImg}}">
								{% else %}
									<img src="/img/default.png" class="w-50 d-block mx-auto" alt="/img/default.png">
								{% endif %}
							{% endif %}
						{% endfor %}
					</div>
				</article>

				<article class="row d-flex justify-content-center col-12 py-3 mx-auto">
					<div class="col-12 mb-2 align-self-center justify-content-center">
						<p>{{page.bloc3|raw}}</p>
					</div>
				</article>

				<hr class="separator-entretien pb-3">
			</div>

			<div class="row d-flex col-lg-4 col-md-12 justify-content-center ml-2 vr align-self-center">
				<h4>
					<font color="#cc0000">Forfaits</font>
				</h4>
				<article class="row d-flex justify-content-center align-self-center col-12 py-5">

					{% for forfait in forfaits %}

						<div class="col-9">{{forfait.libForfait}}</div>
						<div class="col-3 text-right">
							<font color="#cc0000">
								{{forfait.prixForfait}}
								€
							</font>
						</div>

					{% endfor %}
				</article>
			</div>

			{# <div class="phone-services">
				<i class='fa fa-phone'></i>
			</div> #}

		</section>

	</main>
{% endblock %}