src/Entity/ThemesFAQ.php
<?php

namespace App\Entity;

use App\Repository\ThemesFAQRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ThemesFAQRepository::class)
 */
class ThemesFAQ
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $theme_question;

    /**
     * @ORM\OneToMany(targetEntity=FAQ::class, mappedBy="theme_FAQ")
     */
    private $fAQs;

    public function __construct()
    {
        $this->fAQs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getThemeQuestion(): ?string
    {
        return $this->theme_question;
    }

    public function setThemeQuestion(string $theme_question): self
    {
        $this->theme_question = $theme_question;

        return $this;
    }

    /**
     * @return Collection|FAQ[]
     */
    public function getFAQs(): Collection
    {
        return $this->fAQs;
    }

    public function addFAQ(FAQ $fAQ): self
    {
        if (!$this->fAQs->contains($fAQ)) {
            $this->fAQs[] = $fAQ;
            $fAQ->setThemeFAQ($this);
        }

        return $this;
    }

    public function removeFAQ(FAQ $fAQ): self
    {
        if ($this->fAQs->removeElement($fAQ)) {
            // set the owning side to null (unless already changed)
            if ($fAQ->getThemeFAQ() === $this) {
                $fAQ->setThemeFAQ(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return (string) $this->theme_question;
    }
}

src/Form/ThemesFAQType.php
<?php

namespace App\Form;

use App\Entity\ThemesFAQ;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ThemesFAQType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('theme_question', TextType::class, [
                "label" => "Thème de questions en FAQ"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ThemesFAQ::class,
        ]);
    }
}

src/Controller/ThemesFAQController.php
<?php

namespace App\Controller;

use App\Entity\ThemesFAQ;
use App\Form\ThemesFAQType;
use App\Repository\ThemesFAQRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/admin/themes_faq")
 * @IsGranted("ROLE_ADMIN")
 */
class ThemesFAQController extends AbstractController
{
    /**
     * @Route("/", name="themes_faq_index", methods={"GET"})
     */
    public function index(ThemesFAQRepository $themesFAQRepository): Response
    {
        return $this->render('themes_faq/index.html.twig', [
            'themes_faqs' => $themesFAQRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="themes_faq_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $themesFAQ = new ThemesFAQ();
        $form = $this->createForm(ThemesFAQType::class, $themesFAQ);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $formatThemeQuestion = $themesFAQ->getThemeQuestion();
            $formatThemeQuestion = trim(ucfirst(mb_convert_case($formatThemeQuestion, MB_CASE_LOWER)));
            $themesFAQ->setThemeQuestion($formatThemeQuestion);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($themesFAQ);
            $entityManager->flush();

            $this->addFlash('success', 'La thématique a bien été ajoutée !');

            return $this->redirectToRoute('themes_faq_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('themes_faq/new.html.twig', [
            'themes_faq' => $themesFAQ,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="themes_faq_show", methods={"GET"})
     */
    public function show(ThemesFAQ $themesFAQ): Response
    {
        return $this->render('themes_faq/show.html.twig', [
            'themes_faq' => $themesFAQ,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="themes_faq_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, ThemesFAQ $themesFAQ): Response
    {
        $form = $this->createForm(ThemesFAQType::class, $themesFAQ);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $formatThemeQuestion = $themesFAQ->getThemeQuestion();
            $formatThemeQuestion = trim(ucfirst(mb_convert_case($formatThemeQuestion, MB_CASE_LOWER)));
            $themesFAQ->setThemeQuestion($formatThemeQuestion);

            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'La thématique a bien été modifiée !');

            return $this->redirectToRoute('themes_faq_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('themes_faq/edit.html.twig', [
            'themes_faq' => $themesFAQ,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="themes_faq_delete", methods={"POST"})
     */
    public function delete(Request $request, ThemesFAQ $themesFAQ): Response
    {
        if ($this->isCsrfTokenValid('delete'.$themesFAQ->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($themesFAQ);
            $entityManager->flush();
            $this->addFlash('success', 'La thématique a bien été supprimée !');
        } else {
            $this->addFlash('danger', 'Une erreur est survenue !');
        }

        return $this->redirectToRoute('themes_faq_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/themes_faq/_delete_form.html.twig
<form method="post" action="{{ path('themes_faq_delete', {'id': themes_faq.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ themes_faq.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/themes_faq/_form.html.twig
{{ form_start(form) }}
    {{form_label (form.theme_question)}} <font style="color:red">*</font>
    {{form_widget (form.theme_question)}}

    {{ form_widget(form) }}

<button class="btn btn-info mt-3">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/themes_faq/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Modifier les thèmes du FAQ
{% endblock %}

{% block body %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 mb-3">
		<div class="col-12">
			<h1>Modifier le thème du FAQ -
				{{ themes_faq.themeQuestion }}</h1>
			<a href="{{ path('themes_faq_index') }}" class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Retour à la liste
			</a>
		</div>


		<div class="container mt-3">
			{# {{ include('themes_faq/_form.html.twig', {'button_label': 'Update'}) }} #}

				{{ form_start(form)}}
				{{form_label (form.theme_question)}}  <font style="color:red">*</font>
				{{form_widget (form.theme_question)}}
				{{ form_rest(form)}}

			<div class="row mt-3">
				<button type="submit" class="btn btn-info mr-2">
					<i class="fa fa-pen"></i>
					Modifier</button>
				{{ include('themes_faq/_delete_form.html.twig') }}
			</div>
			{{ form_end(form)}}
		</div>

	</main>


{% endblock %}

templates/themes_faq/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Thèmes du FAQ
{% endblock %}

{% block body %}
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 mb-3">
{{parent()}}

		<div class="container-fluid m-2">
			<div class="row d-flex justify-content-between mb-3">
				<h1 class="my-2">Thèmes du FAQ</h1>
				<a href="{{ path('themes_faq_new') }}" class="btn btn-info align-self-center mr-4">
					<i class="fa fa-plus"></i>
					Ajouter</a>
			</div>

			<div class="container-fluid m-2">

			<p class='alert-info p-3'><i class="fa fa-info-circle"></i> Le contenu de cette page se répercute sur la page FAQ et permet de regrouper les duo question/réponses de la table lors du tri automatique de la page FAQ.</p>

				<table class="table table-hover table-striped">
					<thead>
						<tr>
							<th>#</th>
							<th>Thèmes des question</th>
							<th colspan="2">Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for themes_faq in themes_faqs %}
							<tr>
								<td>{{ themes_faq.id }}</td>
								<td>{{ themes_faq.themeQuestion }}</td>
								<td>
									<a href="{{ path('themes_faq_edit', {'id': themes_faq.id}) }}" class="btn btn-info">
										<i class="fa fa-pen"></i>
										Modifier</a>
									<a href="{{ path('themes_faq_delete', {'id': themes_faq.id}) }}" class="btn btn-danger">
										<i class="fa fa-trash-alt"></i>
										Supprimer</a>
								</td>
							</tr>
						{% else %}
							<tr>
								<td colspan="3">no records found</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</main>
{% endblock %}

templates/themes_faq/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Ajouter un thème au FAQ
{% endblock %}

{% block body %}

	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 p-4">
		<div class="col-12 mb-3">
			<h1>Ajouter un thème au FAQ</h1>
			<a href="{{ path('themes_faq_index') }}" class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Retour à la liste</a>
		</div>

		<div class="container mt-2">
			{{ include('themes_faq/_form.html.twig') }}
		</div>
    </main>

	{% endblock %}

templates/themes_faq/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Thèmes du FAQ{% endblock %}

{% block body %}

	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 p-4">
		<div class="col-12">
			<h1>Thème du FAQ -
				{{ themes_faq.themeQuestion }}</h1>
			<a href="{{ path('themes_faq_index') }}" class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Retour à la liste
			</a>
		</div>

		<div class="container my-3">
			<table class="table">
				<tbody>
					<tr>
						<th class="cellwidth">Thème :</th>
						<td>{{ themes_faq.themeQuestion }}</td>
					</tr>
				</tbody>
			</table>

		</div>

		<div class="container">
			<div class="row">
				<a href="{{ path('themes_faq_edit', {'id': themes_faq.id})}}" class="btn btn-info mr-3">
					<i class="fa fa-pen"></i>
					Modifier</a>

				{{ include('themes_faq/_delete_form.html.twig') }}
			</div>
		</div>
	</main>

{% endblock %}