src/Entity/Services.php
<?php

namespace App\Entity;

use App\Repository\ServicesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ServicesRepository::class)
 */
class Services
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lib_service;

    /**
     * @ORM\OneToMany(targetEntity=Forfaits::class, mappedBy="services")
     */
    private $forfaits;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="services")
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=Pages::class, mappedBy="services")
     */
    private $pages;

    public function __construct()
    {
        $this->forfaits = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->pages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibService(): ?string
    {
        return $this->lib_service;
    }

    public function setLibService(string $lib_service): self
    {
        $this->lib_service = $lib_service;

        return $this;
    }

    /**
     * @return Collection|Forfaits[]
     */
    public function getForfaits(): Collection
    {
        return $this->forfaits;
    }

    public function addForfait(Forfaits $forfait): self
    {
        if (!$this->forfaits->contains($forfait)) {
            $this->forfaits[] = $forfait;
            $forfait->setServices($this);
        }

        return $this;
    }

    public function removeForfait(Forfaits $forfait): self
    {
        if ($this->forfaits->removeElement($forfait)) {
            // set the owning side to null (unless already changed)
            if ($forfait->getServices() === $this) {
                $forfait->setServices(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setServices($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getServices() === $this) {
                $image->setServices(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return (string) $this->lib_service;
    }

    /**
     * @return Collection|Pages[]
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(Pages $page): self
    {
        if (!$this->pages->contains($page)) {
            $this->pages[] = $page;
            $page->setServices($this);
        }

        return $this;
    }

    public function removePage(Pages $page): self
    {
        if ($this->pages->removeElement($page)) {
            // set the owning side to null (unless already changed)
            if ($page->getServices() === $this) {
                $page->setServices(null);
            }
        }

        return $this;
    }
}

src/Form/ServicesType.php
<?php

namespace App\Form;

use App\Entity\Services;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ServicesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lib_service', TextType::class, [
                'label' => 'Libellé du service'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Services::class,
        ]);
    }
}

src/Controller/ServicesController.php
<?php

namespace App\Controller;

use App\Entity\Services;
use App\Form\ServicesType;
use App\Repository\ServicesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/admin/services")
 * @IsGranted("ROLE_ADMIN")
 */
class ServicesController extends AbstractController
{
    /**
     * @Route("/", name="services_index", methods={"GET"})
     */
    public function index(ServicesRepository $servicesRepository): Response
    {
        return $this->render('services/index.html.twig', [
            'services' => $servicesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="services_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $service = new Services();
        $form = $this->createForm(ServicesType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $formatLibService = $service->getLibService();
            $formatLibService = trim(ucfirst(mb_convert_case($formatLibService, MB_CASE_LOWER)));
            $service->setLibService($formatLibService);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($service);
            $entityManager->flush();

            $this->addFlash('success', 'Le service a bien été ajouté !');

            return $this->redirectToRoute('services_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('services/new.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="services_show", methods={"GET"})
     */
    public function show(Services $service): Response
    {
        return $this->render('services/show.html.twig', [
            'service' => $service,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="services_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Services $service): Response
    {
        $form = $this->createForm(ServicesType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $formatLibService = $service->getLibService();
            $formatLibService = trim(ucfirst(mb_convert_case($formatLibService, MB_CASE_LOWER)));
            $service->setLibService($formatLibService);

            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'Le service a bien été modifié !');

            return $this->redirectToRoute('services_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('services/edit.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="services_delete", methods={"POST"})
     */
    public function delete(Request $request, Services $service): Response
    {
        if ($this->isCsrfTokenValid('delete' . $service->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($service);
            $entityManager->flush();
            $this->addFlash('success', 'Le service a bien été supprimé !');
        } else {
            $this->addFlash("danger", "Une erreur est survenue !");
        }

        return $this->redirectToRoute('services_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/services/_delete_form.html.twig
<form method="post" action="{{ path('services_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/services/_form.html.twig
{{ form_start(form) }}
    {{form_label (form.lib_service)}} <font style="color:red">*</font>
    {{form_widget (form.lib_service)}}
    <button class="btn btn-info mt-3">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/services/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Modifier les services{% endblock %}

{% block body %}

	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 mb-3">
		<div class="col-12">
			<h1>Modifier le service ou la catégorie de page(s) -	{{ service.libService }}</h1>
			<a href="{{ path('services_index') }}" class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Retour à la liste
			</a>
		</div>


		<div class="container mt-3">
			{{ form_start(form)}}
			{{form_label (form.lib_service)}} <font style="color:red">*</font>
			{{form_widget (form.lib_service)}}
			{{ form_rest(form)}}
			<div class="row mt-3">
				<button type="submit" class="btn btn-info mr-2">
					<i class="fa fa-pen"></i>
					Modifier</button>
				{{ include('services/_delete_form.html.twig') }}
			</div>
			{{ form_end(form)}}
		</div>

	</main>

{% endblock %}

templates/services/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Services
{% endblock %}

{% block body %}
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 mb-3">
 		{{parent()}}
		<div class="container-fluid m-2">
			<div class="row d-flex justify-content-between mb-3">
				<h1 class="my-2">Services et catégories de pages</h1>
				<a href="{{ path('services_new') }}" class="btn btn-info align-self-center mr-4">
					<i class="fa fa-plus"></i>
					Ajouter</a>
			</div>

			<div class="container-fluid m-2">

				<p class='alert-info p-3'>
					<i class="fa fa-info-circle"></i>
					Le contenu de cette page permet de définir sur quelle page de services (restauration, passage au banc, entretien, préparation et personnalisation) les forfaits seront affichés.</p>

				<table class="table table-hover table-striped">
					<thead>
						<tr>
							<th>#</th>
							<th>Services et catégories de pages</th>
							<th colspan="2">Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for service in services %}
							<tr>
								<td>{{ service.id }}</td>
								<td>{{ service.libService }}</td>
								<td>
									<a href="{{ path('services_edit', {'id': service.id}) }}" class="btn btn-info">
										<i class="fa fa-pen"></i>
										Modifier</a>
									<a href="{{ path('services_delete', {'id': service.id}) }}" class="btn btn-danger">
										<i class="fa fa-trash-alt"></i>
										Supprimer</a>
								</td>
							</tr>
						{% else %}
							<tr>
								<td colspan="3">no records found</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</main>

{% endblock %}

templates/services/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un service
{% endblock %}

{% block body %}
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 p-4">
		<div class="col-12 mb-3">
			<h1>Ajouter un service ou une catégorie de pages</h1>
			<a href="{{ path('services_index') }}" class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Retour à la liste</a>
		</div>

		<div class="container mt-2">
			{{ include('services/_form.html.twig') }}
		</div>

	{% endblock %}

templates/services/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Services et catégories de pages
{% endblock %}

{% block body %}

	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 p-4">
		<div class="col-12">
			<h1>Services -
				{{ service.libService }}</h1>
			<a href="{{ path('services_index') }}" class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Retour à la liste
			</a>
		</div>

		<div class="container my-3">
			<table class="table">
				<tbody>
					<tr>
						<th class="cellwidth">Service ou catégorie de page(s) :</th>
						<td>{{ service.libService }}</td>
					</tr>
				</tbody>
			</table>

		</div>

		<div class="container">
			<div class="row">
				<a href="{{ path('services_edit', {'id': service.id})}}" class="btn btn-info mr-3">
					<i class="fa fa-pen"></i>
					Modifier</a>

				{{ include('services/_delete_form.html.twig') }}
			</div>
		</div>
	</main>

{% endblock %}