src/Entity/Couleurs.php
<?php

namespace App\Entity;

use App\Repository\CouleursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CouleursRepository::class)
 */
class Couleurs
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lib_couleur;

    /**
     * @ORM\ManyToMany(targetEntity=Modeles::class, mappedBy="couleurs")
     */
    private $modeles;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $img_color;

    public function __construct()
    {
        $this->modeles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibCouleur(): ?string
    {
        return $this->lib_couleur;
    }

    public function setLibCouleur(string $lib_couleur): self
    {
        $this->lib_couleur = $lib_couleur;

        return $this;
    }

    /**
     * @return Collection|Modeles[]
     */
    public function getModeles(): Collection
    {
        return $this->modeles;
    }

    public function addModele(Modeles $modele): self
    {
        if (!$this->modeles->contains($modele)) {
            $this->modeles[] = $modele;
            $modele->addCouleur($this);
        }

        return $this;
    }

    public function removeModele(Modeles $modele): self
    {
        if ($this->modeles->removeElement($modele)) {
            $modele->removeCouleur($this);
        }

        return $this;
    }

    public function getImgColor(): ?string
    {
        return $this->img_color;
    }

    public function setImgColor(?string $img_color): self
    {
        $this->img_color = $img_color;

        return $this;
    }

    public function __toString() {
        return (string) $this->lib_couleur;
    }
}

src/Form/CouleursType.php
<?php

namespace App\Form;

use App\Entity\Couleurs;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class CouleursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lib_couleur', TextType::class, [
                "label" => "Nom de la couleur"
            ])
            ->add('img_color', FileType::class, [
                "label" => "Image de la couleur", 
                "required" => false,
                "mapped"=> false,
                "help" => 'Utiliser des fichiers .png, .jpg, .jpeg, .svg ou .gif',
                "attr" => [
                    'lang'=>'fr', 
                    'class' => 'form-control-file'
                ], 
                'constraints' => [
                    new File([
                        'maxSize' => '10240k',
                        'maxSizeMessage' => "Votre fichier est trop grand. Merci de charger un fichier de moins de 4Mo.",
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/jpg',
                            'image/png',
                            'image/svg+xml',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => 'Merci de télécharger vos fichiers avec une extension .png, .jpg, .jpeg, .svg ou .gif',
                    ])
                ],
            ])
            // ->add('modeles')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Couleurs::class,
        ]);
    }
}

src/Controller/CouleursController.php
<?php

namespace App\Controller;

use App\Entity\Couleurs;
use App\Form\CouleursType;
use App\Repository\CouleursRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/admin/couleurs")
 * @IsGranted("ROLE_ADMIN")
 */
class CouleursController extends AbstractController
{
    /**
     * @Route("/", name="couleurs_index", methods={"GET"})
     */
    public function index(CouleursRepository $couleursRepository): Response
    {
        return $this->render('couleurs/index.html.twig', [
            'couleurs' => $couleursRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="couleurs_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $couleur = new Couleurs();
        $form = $this->createForm(CouleursType::class, $couleur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $formatLibCouleur = $couleur->getLibCouleur();
            $formatLibCouleur = trim(ucfirst(strtolower($formatLibCouleur)));
            $couleur->setLibCouleur($formatLibCouleur);

            $file = $form->get('img_color')->getData();

            if ($file) {
                $uploadedfile = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $uploadedfile = "paint-" . $_POST["couleurs"]["lib_couleur"];
                $uploadedfile = str_replace(" ", "_", $uploadedfile);
                $uploadedfile .= "_" . uniqid() . "." . $file->guessExtension();
                $file->move('img/', $uploadedfile);
                $couleur->setImgColor($uploadedfile);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($couleur);
            $entityManager->flush();

            $this->addFlash('success', 'La couleur a bien été ajoutée !');

            return $this->redirectToRoute('couleurs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('couleurs/new.html.twig', [
            'couleur' => $couleur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="couleurs_show", methods={"GET"})
     */
    public function show(Couleurs $couleur): Response
    {
        return $this->render('couleurs/show.html.twig', [
            'couleur' => $couleur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="couleurs_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Couleurs $couleur): Response
    {
        $form = $this->createForm(CouleursType::class, $couleur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $formatLibCouleur = $couleur->getLibCouleur();
            $formatLibCouleur = trim(ucfirst(strtolower($formatLibCouleur)));
            $couleur->setLibCouleur($formatLibCouleur);

            $file = $form->get('img_color')->getData();

            if ($file) {
                $uploadedfile = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $uploadedfile = "paint-" . $_POST["couleurs"]["lib_couleur"];
                $uploadedfile = str_replace(" ", "_", $uploadedfile);
                $uploadedfile .= "_" . uniqid() . "." . $file->guessExtension();
                $file->move('img/', $uploadedfile);
                $couleur->setImgColor($uploadedfile);
            }


            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'La couleur a bien été modifiée !');

            return $this->redirectToRoute('couleurs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('couleurs/edit.html.twig', [
            'couleur' => $couleur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="couleurs_delete", methods={"POST"})
     */
    public function delete(Request $request, Couleurs $couleur): Response
    {
        if ($this->isCsrfTokenValid('delete' . $couleur->getId(), $request->request->get('_token'))) {
            $file = $couleur->getImgColor();

            if ($file!=null && file_exists('img/' . $file)) {
                unlink('img/' . $file);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($couleur);
            $entityManager->flush();
            $this->addFlash('success', 'La couleur a bien été supprimée !');
        } else {
            $this->addFlash('danger', 'Une erreur est survenue !');
        }

        return $this->redirectToRoute('couleurs_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/couleurs/_delete_form.html.twig
<form method="post" action="{{ path('couleurs_delete', {'id': couleur.id}) }}" onsubmit="return confirm('Êtes-vous sûr(e) de vouloir supprimer cet élément ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ couleur.id) }}">
    <button class="btn btn-danger"> <i class="fa fa-trash"></i> Supprimer</button>
</form>

templates/couleurs/_form.html.twig
{{ form_start(form) }}

    <div class="mb-3">
    {{form_label (form.lib_couleur)}} <font style="color:red">*</font>
    {{form_widget (form.lib_couleur)}}
    </div>

    <div class="mb-3">
    {{form_label (form.img_color)}} <font style="color:red">*</font>
    {{form_widget (form.img_color)}}
    {{form_help (form.img_color)}}
    </div>

    {{ form_rest(form) }}
    <button class="btn btn-info">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/couleurs/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la couleur
{% endblock %}

{% block body %}
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 mb-3">
		<div class="col-12">
			<h1>Modifier la couleur -
				{{ couleur.libCouleur }}</h1>
			<a href="{{ path('couleurs_index') }}" class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Retour à la liste
			</a>
		</div>

		<div class="container mt-3">
			{{form_start(form)}}
			<div class="mb-3">
				{{form_label (form.lib_couleur)}}
				<font style="color:red">*</font>
				{{form_widget (form.lib_couleur)}}
			</div>

			<div class="mb-3">
				{{form_label (form.img_color)}}
				<font style="color:red">*</font>
				<div>
					{% if couleur.imgColor != "" %}
						<img src="/img/{{ couleur.imgColor }}" alt="{{ couleur.libCouleur }}" class="mb-2 img-edit">
					{% else %}
						<img src="/img/default.png" alt="default_image" class="mb-2 img-edit">
					{% endif %}
					{{form_widget (form.img_color, {'attr' : {'class': 'inline' }})}}
					{{form_help (form.img_color)}}
				</div>
			</div>

			{{ form_rest(form)}}
			<div class="row mt-3">
				<button type="submit" class="btn btn-info mr-2">
					<i class="fa fa-pen"></i>
					Modifier</button>
				<a href="{{path('couleurs_delete', {'id':couleur.id})}}" class="btn btn-danger mr-2">
					<i class="fa fa-trash"></i>
					Supprimer</a>
			</div>
			{{ form_end(form)}}

		</div>

	</main>
{% endblock %}

templates/couleurs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Couleurs
{% endblock %}

{% block body %}
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 mb-3">
{{parent()}}
		<div class="container-fluid m-2">
			<div class="row d-flex justify-content-between mb-3">
				<h1 class="my-2">Couleurs</h1>
				<a href="{{ path('couleurs_new') }}" class="btn btn-info align-self-center mr-4">
					<i class="fa fa-plus"></i>
					Ajouter</a>
			</div>

			<div class="container-fluid m-2">

			<p class='alert-info p-3'><i class="fa fa-info-circle"></i> Le contenu de cette page se répercute sur les pages modèles de moto.</p>
			
				<table class="table table-hover table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Couleur</th>
								<th>Représentation</th>
								<th colspan="2">Actions</th>
							</tr>
						</thead>
						<tbody>
							{% for couleur in couleurs %}
								<tr>
									<td class='align-middle'>{{ couleur.id }}</td>
									<td class='align-middle' class="cellwidthimg">{{ couleur.libCouleur }}</td>
									<td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">
										{% if couleur.imgColor != "" %}
											<img src="/img/{{ couleur.imgColor }}" alt="{{ couleur.libCouleur }}" class="img-prez img-fluid mx-auto">
										{% else %}
											<img src="/img/default.png" alt="default_image" class="img-prez img-fluid mx-auto">
										{% endif %}
									</td>
									<td class='align-middle flex-nowrap align-self-auto'>
										<a href="{{ path('couleurs_edit', {'id': couleur.id}) }}" class="btn btn-info">
											<i class="fa fa-pen"></i>
											Modifier</a>
										<a href="{{ path('couleurs_delete', {'id': couleur.id}) }}" class="btn btn-danger">
											<i class="fa fa-trash-alt"></i>
											Supprimer</a>
									</td>
								
								</tr>
							{% else %}
								<tr>
									<td colspan="4">no records found</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>


		</main>
	{% endblock %}

templates/couleurs/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une couleur{% endblock %}

{% block body %}

	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 p-4">
		<div class="col-12 mb-3">
			<h1>Ajouter une couleur</h1>
			<a href="{{ path('couleurs_index') }}" class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Retour à la liste</a>
		</div>

		<div class="container mt-2">
			{{ include('couleurs/_form.html.twig') }}
		</div>


	</main>
{% endblock %}

templates/couleurs/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Couleurs{% endblock %}

{% block body %}
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 p-4">
		<div class="col-12">
			<h1>Couleurs -
				{{ couleur.libCouleur }}
			</h1>
			<a href="{{ path('couleurs_index') }}" class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Retour à la liste
			</a>
		</div>
		<div class="container my-3">
			<table class="table">
				<tbody>
            <tr>
                <th>Lib_couleur</th>
                <td>{{ couleur.libCouleur }}</td>
            </tr>
            <tr>
						<th class="cellwidth">Logo :</th>
						<td>
							{% if couleur.imgColor != "" %}
								<img src="/img/{{ couleur.imgColor }}" alt="{{ couleur.libCouleur }}" class="w-25 img-fluid">
							{% else %}
								<img src="/img/default.png" alt="default_image" class="w-25 img-fluid">
							{% endif %}
						</td>
					</tr>
				</tbody>
			</table>
		</div>

		<div class="container">
			<div class="row">
				<a href="{{ path('couleurs_edit', {'id': couleur.id})}}" class="btn btn-info mr-3">
					<i class="fa fa-pen"></i>
					Modifier</a>

				{{ include('couleurs/_delete_form.html.twig') }}
			</div>
		</div>

	</main>
{% endblock %}